before_commands:
    - "composer install --prefer-dist"

tools:
    php_mess_detector: true
    php_code_sniffer: true
    php_analyzer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend: true
