language: php

sudo: false

php:
  - 5.3
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=2.7.*
    - SYMFONY_VERSION=2.8.*
    - SYMFONY_VERSION=3.0.*

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar require symfony/class-loader:${SYMFONY_VERSION} --no-update
    - php composer.phar require symfony/yaml:${SYMFONY_VERSION} --no-update
    - php composer.phar require symfony/security-bundle:${SYMFONY_VERSION} --no-update
    - php composer.phar require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - php composer.phar update --dev --no-interaction

script:
  - php vendor/bin/behat
