language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=2.4.*
    - SYMFONY_VERSION=2.5.*
    - SYMFONY_VERSION=2.6.*

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar require symfony/class-loader:${SYMFONY_VERSION} --no-update
    - php composer.phar require symfony/yaml:${SYMFONY_VERSION} --no-update
    - php composer.phar require symfony/security-bundle:${SYMFONY_VERSION} --no-update
    - php composer.phar require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - php composer.phar update --dev --no-interaction

script:
  - php vendor/bin/behat
